In [1]:
import numpy as np

# arange - Arrays con secuencia y paso

In [2]:
my_array = np.arange(0,10,2)

In [3]:
my_array

array([0, 2, 4, 6, 8])

In [4]:
print(type(my_array))

<class 'numpy.ndarray'>


# array - Arrays definidos

In [5]:
my_array_int = np.array([1,2,3])

In [6]:
print(my_array_int)

[1 2 3]


In [7]:
print(type(my_array_int))

<class 'numpy.ndarray'>


En ambos casos con el método __array__ o __arange__ se obtiene un objeto _numpy.ndarray_

¿Por qué array y no list? Porque los objetos numpy.ndarray tiene un manejo mas eficiente en la memoria. Esto se debe también a aque con un objeto tipo list se pueden guardar distintos tipos de datos en un mismo array: boolean, string, int, etc. Mientras que con numpy.ndarray solo se utiliza un solo tipo de dato. Esta caracteristica hace que se ahorre memoria en un programa.

In [8]:
my_array_str = np.array([1,'dos',3])

In [9]:
print(my_array_str)

['1' 'dos' '3']


In [10]:
print(type(my_array_str[1]))

<class 'numpy.str_'>


In [11]:
print(type(my_array_int[1]))

<class 'numpy.int32'>


## Especificar el tamaño del tipo de dato

In [12]:
array_int8 = np.array([1,2,3], dtype=np.int8)

In [13]:
array_int64 = np.array([1,2,3], dtype=np.int64)

In [14]:
print(type(array_int8[0]))

<class 'numpy.int8'>


In [15]:
print(type(array_int64[0]))

<class 'numpy.int64'>


En este ejemplo, el objeto _numpy.ndarray_ almacena en cada posición distintos tipos de datos, siendo int8 un consumo menor de memoria que int64. Esto se debe pensar desde la lógica binaria, ya que int8 permite utilizar hasta 8 bits de información 2^8=256, mientras que int64 llega a 2^64=1.846e19. Lo cual logicamente quiere decir que int64 puede guardar muchos mas números pero a costo de utilizar mucha mas memoria, lo cual puede ser ineficiente dependiendo del tipo de dato que se utilice.

La variable __array_int8__ puede almacenar un numero del 0 al 255, es decir 256 objetos. ¿Que pasa si se coloca el número 500 en una posición?

In [16]:
array_int8 = np.array([500,2,3], dtype=np.int8)

In [17]:
print(array_int8)

[-12   2   3]


Los datos no se muestran correctamente, una vez que se excede el 255 el número vuelve a 0.

# 2D arrays

Se pueden crear arrays de n dimensiones, tal como sería una matriz

In [18]:
array_two_dim = np.array([[1,2,3],[3,4,5]])

In [19]:
array_two_dim

array([[1, 2, 3],
       [3, 4, 5]])

In [20]:
type(array_two_dim)

numpy.ndarray

Se puede crear tambien cada fila como secuencia

In [21]:
array_2d_seq = np.array([np.arange(0,8,2), np.arange(1,8,2)], dtype=np.int8)

In [22]:
print(array_2d_seq)

[[0 2 4 6]
 [1 3 5 7]]


## Dimensión de un array

In [23]:
print("2 row, 4 col:", array_2d_seq.shape)

2 row, 4 col: (2, 4)


In [24]:
print("3 row, 0 col:", array_int64.shape)

3 row, 0 col: (3,)


# Redimensionamiento

El array _array_2d_seq_ puede redimensionarse de un tipo 2x4 a un array 4x2

In [25]:
array_2d_seq.reshape(4,2)

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]], dtype=int8)

Tambien se puede redimensionar a un array de 8 rows

In [26]:
array_2d_seq.reshape(8)

array([0, 2, 4, 6, 1, 3, 5, 7], dtype=int8)

# Arrays de ceros

Se puede crear un array de n dimensiones con puros ceros con el método _zeros_

In [27]:
zeros_array = np.zeros((2,2))

In [28]:
print(zeros_array)

[[0. 0.]
 [0. 0.]]


# Arrays de unos

De igual forma, se puede crear uno lleno de unos con el método _ones_

In [29]:
ones_array = np.ones((2,2))

In [30]:
print(ones_array)

[[1. 1.]
 [1. 1.]]


# Empty arrays o arrays random

Con el método _empty_ se puede construir arrays con datos flotantes de valores aleatorios

In [31]:
empty_array = np.empty((2,2))

In [32]:
print(empty_array)

[[1. 1.]
 [1. 1.]]


In [33]:
random_array = np.empty((2,2,2))

In [34]:
print(random_array)

[[[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 8.35959073e-321]
  [1.05699242e-307 8.01097888e-307]]]


# Matriz identidad

Con el métoco _eye_ se puede construir matrices identidades de n dimension como argumento

In [35]:
id_matrix = np.eye(10, dtype=np.int8)

In [36]:
print(id_matrix)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


También es posible desplazar la diagonal con el argumento _k_ en el método

In [37]:
id_matrix = np.eye(10, k=-1, dtype=np.int8)

In [38]:
print(id_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]]


## Reemplazo de valores en un array a traves de condiciones

In [39]:
id_matrix[id_matrix == 0] = 9 

In [40]:
print(id_matrix)

[[9 9 9 9 9 9 9 9 9 9]
 [1 9 9 9 9 9 9 9 9 9]
 [9 1 9 9 9 9 9 9 9 9]
 [9 9 1 9 9 9 9 9 9 9]
 [9 9 9 1 9 9 9 9 9 9]
 [9 9 9 9 1 9 9 9 9 9]
 [9 9 9 9 9 1 9 9 9 9]
 [9 9 9 9 9 9 1 9 9 9]
 [9 9 9 9 9 9 9 1 9 9]
 [9 9 9 9 9 9 9 9 1 9]]


## Remplazo de valores de una o varias filas

In [41]:
id_matrix[0:2] = 0

Se reemplaza desde la fila 0 a 1 con el valor 0

In [42]:
print(id_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [9 1 9 9 9 9 9 9 9 9]
 [9 9 1 9 9 9 9 9 9 9]
 [9 9 9 1 9 9 9 9 9 9]
 [9 9 9 9 1 9 9 9 9 9]
 [9 9 9 9 9 1 9 9 9 9]
 [9 9 9 9 9 9 1 9 9 9]
 [9 9 9 9 9 9 9 1 9 9]
 [9 9 9 9 9 9 9 9 1 9]]


## Remplazo de valores de una o varias columnas

Se remplazan los valores desde la columna 0 a 1

In [43]:
id_matrix[:, 0:2] = 0

In [44]:
print(id_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 9 9 9 9 9 9 9 9]
 [0 0 1 9 9 9 9 9 9 9]
 [0 0 9 1 9 9 9 9 9 9]
 [0 0 9 9 1 9 9 9 9 9]
 [0 0 9 9 9 1 9 9 9 9]
 [0 0 9 9 9 9 1 9 9 9]
 [0 0 9 9 9 9 9 1 9 9]
 [0 0 9 9 9 9 9 9 1 9]]


De forma similar se puede cambiar los valores de una columna o fila sola en especifico. Por ejemplo la columna 3,

In [45]:
id_matrix[:,3]=34

In [46]:
print(id_matrix)

[[ 0  0  0 34  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0]
 [ 0  0  9 34  9  9  9  9  9  9]
 [ 0  0  1 34  9  9  9  9  9  9]
 [ 0  0  9 34  9  9  9  9  9  9]
 [ 0  0  9 34  1  9  9  9  9  9]
 [ 0  0  9 34  9  1  9  9  9  9]
 [ 0  0  9 34  9  9  1  9  9  9]
 [ 0  0  9 34  9  9  9  1  9  9]
 [ 0  0  9 34  9  9  9  9  1  9]]


# Ordenar array

Con el método _np.sort_ es posible ordenar cada una de las filas de un array, pasando como argumento el array a ordenar. Este metodo crea un nuevo objeto _numpy.array_ pero no modifica el objeto ya creado que no se encuentra en orden.

In [47]:
disorder_array = np.array([[1, 2, -1], [23, 45, 22], [0, 99, 5]])

In [48]:
print(disorder_array)

[[ 1  2 -1]
 [23 45 22]
 [ 0 99  5]]


In [49]:
sorted_array = np.sort(disorder_array)

In [50]:
print(sorted_array)

[[-1  1  2]
 [22 23 45]
 [ 0  5 99]]


También es posible modificar el orden de un array pero a traves de sus columnas

In [51]:
sorted_array_by_col = np.sort(disorder_array, axis=0)

In [52]:
print(sorted_array_by_col)

[[ 0  2 -1]
 [ 1 45  5]
 [23 99 22]]


# Copiar arrays

## Copia de referencias con método _view_ 

In [53]:
array1 = np.array([[1,2,3],[22,3,4]])

In [54]:
array2_view = array1.view()

In [55]:
print(array1, '\n')
print(array2_view, '\n')

[[ 1  2  3]
 [22  3  4]] 

[[ 1  2  3]
 [22  3  4]] 



Con el método _view_ se puede copiar los valores, pero en realidad se copian las referencias del banco de memoria. Al modificar __array2_view__ se modifica también __array1__

In [56]:
array2_view[:]=44
print(array2_view,'\n')
print(array1)

[[44 44 44]
 [44 44 44]] 

[[44 44 44]
 [44 44 44]]


## Copia de valores a un nuevo espacio de memoria con método _copy_ 

In [57]:
array1 = np.array([[1,2,3],[22,3,4]])

In [58]:
array2_copy = array1.copy()
print(array2_copy,'\n')
print(array1,'\n')

[[ 1  2  3]
 [22  3  4]] 

[[ 1  2  3]
 [22  3  4]] 



Al modificar __array2_copy__ se modifica solo esta variable ya que es un nuevo banco de memoria independiente.

In [59]:
array2_copy[:]=4
print(array2_copy,'\n')
print(array1, '\n')

[[4 4 4]
 [4 4 4]] 

[[ 1  2  3]
 [22  3  4]] 

